import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/layout/_header/navbar";
import { ThemeProvider } from "@/components/layout/_theme/theme-provider";
import { Footer } from "@/components/layout/_footer/footer";

const googleSans = localFont({
  src: [
    {
      path: "../public/fonts/GoogleSans-Bold.ttf",
    },
    {
      path: "../public/fonts/GoogleSans-Medium.ttf",
    },
    {
      path: "../public/fonts/GoogleSans-Regular.ttf",
    },
  ],
});

export const metadata: Metadata = {
  title: "LMS SITE MANAGEMENT SYSTEM",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${googleSans.className} antialiased min-h-screen flex flex-col`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header
            suppressHydrationWarning
            className="sticky top-0 backdrop-blur-sm z-50 bg-white/60 dark:bg-[#243343]/70"
          >
            <Navbar />
          </header>

          <main className="flex-1 max-w-7xl mx-auto w-full px-5 lg:px-14">
            {children}
          </main>

          <footer suppressHydrationWarning>
            <Footer />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
